### ISSUE TITLE
i am running into error

### ISSUE THREAD

**Issue by YASSERRMD** [lucastononro/llm-food-delivery#3]
![image](https://github.com/lucastononro/llm-food-delivery/assets/17435971/1f959739-b19c-4e82-97b0-be9d21dac815)
 
 i am getting while python pinecone_restaurants.py
 
 i just ignored and started the docker compose i am not able to chat always getting this error "Oops there was an error, please try again"

![image](https://github.com/lucastononro/llm-food-delivery/assets/17435971/969ea8ea-ead4-4218-bc64-082f0bdfe11b)

let me know where i am doing wrong, i checked the pinecone for the embedding, i have found the records in auto-food-order index

**Comment by 0xcaffeinated** [comment]
The debugger is active, get rid of `breakpoint()` line and rebuild the image and it should work

**Comment by YASSERRMD** [comment]
thank you but still i am having the chat error

![image](https://github.com/lucastononro/llm-food-delivery/assets/17435971/ef16e8f4-bb35-4754-ba52-7e3c3b8a681f)

**Comment by 0xcaffeinated** [comment]
Did we run the docker compose command within the backend folder? Would you be able to share the container logs? @YASSERRMD

**Comment by YASSERRMD** [comment]
i am running it from the root not from the backend, the container logs

Frontend

![image](https://github.com/lucastononro/llm-food-delivery/assets/17435971/7c86fb3c-83e4-422d-bdca-6d9f319a71bf)


Backend

![image](https://github.com/lucastononro/llm-food-delivery/assets/17435971/dcf61dc7-66a6-4e68-ae65-34b3b3ce5637)

**Comment by 0xcaffeinated** [comment]
did we create an index in pinecone and load the data using the scripts mentioned in the [README.md](https://github.com/lucastononro/llm-food-delivery?tab=readme-ov-file#32-create-a-database-and-populate-it)?

**Comment by lucastononro** [comment]
Try to comment out the @retry decorator to see the actual error
Have you ran the pypoetry to install the libs?

**Comment by lucastononro** [comment]
https://github.com/lucastononro/llm-food-delivery/blob/main/backend/src/services/openai_service/chat_completion.py - comment the retry error out and see if it shows something more actionable

**Comment by YASSERRMD** [comment]
gpt-4-32k is th culprit which is not listed in the v1 endpoint of the model, when i change to gpt-4 it works perfectly, thank you for the support
