### ISSUE TITLE
some errors

### ISSUE THREAD

**Issue by leavenotrace** [lucastononro/llm-food-delivery#4]
nginx-1     | 172.18.0.1 - - [03/Jan/2024:15:59:32 +0000] "GET /?vscodeBrowserReqId=1704297571511 HTTP/1.1" 200 609 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.85.1 Chrome/114.0.5735.289 Electron/25.9.7 Safari/537.36"
frontend-1  | Failed to resolve import "./Navbar/NavBar.vue" from "src/components/AppContainer.vue". Does the file exist?
nginx-1     | 172.18.0.1 - - [03/Jan/2024:15:59:33 +0000] "GET /@vite/client HTTP/1.1" 304 0 "http://127.0.0.1/?vscodeBrowserReqId=1704297571511" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.85.1 Chrome/114.0.5735.289 Electron/25.9.7 Safari/537.36"
frontend-1  | 3:59:33 PM [vite] error while updating dependencies:
frontend-1  | Error: EACCES: permission denied, mkdir '/app/node_modules/.vite/deps_temp_d2f1e065'
frontend-1  |     at Object.mkdirSync (node:fs:1386:3)
frontend-1  |     at runOptimizeDeps (file:///app/node_modules/vite/dist/node/chunks/dep-68d1a114.js:45821:10)
frontend-1  |     at runOptimizer (file:///app/node_modules/vite/dist/node/chunks/dep-68d1a114.js:45267:38)
frontend-1  |     at rerun (file:///app/node_modules/vite/dist/node/chunks/dep-68d1a114.js:45400:9)
frontend-1  |     at Timeout._onTimeout (file:///app/node_modules/vite/dist/node/chunks/dep-68d1a114.js:45470:17)
frontend-1  |     at listOnTimeout (node:internal/timers:559:17)
frontend-1  |     at processTimers (node:internal/timers:502:7)

**Comment by lucastononro** [comment]
Thanks I will review it pretty soon.
It is something with the way we are importing some of the components

**Comment by haimh** [comment]
```frontend-1 | Failed to resolve import "./Navbar/NavBar.vue" from```
You should double check typo in this command. In my case it missed the `B` in upper case. After fixing, it worked like a champ <3

Hope that help.
